services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus-config.yml'
      - '--storage.tsdb.retention.time=4w'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus-config.yml
      - prom_data:/prometheus
volumes:
  prom_data:
